format = """
[](fg:#7aa2f7)\
$time\
[ ](fg:#7aa2f7 bg:#1a1b26)\
$direnv\
$directory\
$git_branch\
$git_status\
$git_metrics\
[](fg:#1a1b26)\
$fill\
[](fg:#1a1b26)\
$cmd_duration\
[](fg:#9ece6a bg:#1a1b26)\
$nodejs\
$golang\
$swift\
[](fg:#9ece6a)\
\n$character\
"""

[time]
format = "[ $time]($style)"
style = 'fg:#1a1b26 bg:#7aa2f7'
time_format = '%T'
utc_time_offset = '+9'
disabled = false

[direnv]
format = '[$symbol$allowed]($style) '
style = "bold fg:#1a1b26 bg:#cba6f7"
disabled = false

[directory]
truncation_length = 6
truncation_symbol = '  '
truncate_to_repo = false
home_symbol = ' ~'
style = 'fg:#7aa2f7 bg:#1a1b26'
read_only = ' 󰌾 '
read_only_style = 'fg:#f7768e bg:#1a1b26'
format = '[$path]($style)[$read_only]($read_only_style)'

[git_branch]
symbol = '  ' # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 4
truncation_symbol = ''
style = 'fg:#7aa2f7 bg:#1a1b26'
format = '[  $symbol$branch(:$remote_branch)]($style)' # nf-pl-left_soft_divider

[git_status]
style = 'fg:#e0af68 bg:#1a1b26'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '([\[$all_status$ahead_behind\]]($style))'

[git_metrics]
added_style = 'fg:#9ece6a bg:#1a1b26'
deleted_style = 'fg:#9ece6a bg:#1a1b26'
format = '[+$added/-$deleted]($deleted_style)'
disabled = false

[fill]
symbol = '─'
style = 'blue'

[cmd_duration]
min_time = 1
style = 'fg:#e0af68 bg:#1a1b26'
format = "[ $duration ]($style)"

[golang]
style = 'fg:#1a1b26 bg:#9ece6a'
format = '[󰟓 ($version )]($style)'

[swift]
style = 'fg:#1a1b26 bg:#9ece6a'
format = '[ ($version )]($style)'
